repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-django==1.1.2
        - flake8-isort==4.1.1
        - flake8-logging-format==0.6.0
        - wemake-python-styleguide==0.16.1
  - repo: local
    hooks:
      - id: mypy
        language: system
        name: mypy
        entry: bash -c "mypy ."
        types: ["python"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: migrations
        entry: bash -c "./manage.py makemigrations --check --dry-run"
        types: ["python"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: django-check
        language: system
        name: django
        entry: bash -c "./manage.py check"
        types: ["python"]
        pass_filenames: false
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
