repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-isort==4.1.1
        - flake8-quotes==3.3.1
  - repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: npx eslint
        language: node
        files: \.(js|jsx)$
  - repo: local
    hooks:
    -   id: stylelint
        name: stylelint
        entry: npx stylelint
        language: node
        files: \.(css|scss|sass)$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    sha: v1.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
