repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: mypy
        language: system
        name: mypy
        entry: bash -c "mypy ."
        types: ["python"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: migrations
        entry: bash -c "./manage.py makemigrations --check --dry-run"
        types: ["python"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: django-check
        language: system
        name: django
        entry: bash -c "./manage.py check"
        types: ["python"]
        pass_filenames: false
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
