version: "3.8"

services:
  db:
    image: "postgres:16-alpine"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - "5432:5432"


  redis:
    image: "redis:7.2-alpine"
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  pg_data:
