[tool.poetry]
name = "django-starter"
version = "0.1.0"
description = ""
authors = ["Alexander Skrivanos <alex@skrivanos.se>"]

[tool.poetry.dependencies]
python = "3.9.11"

# Django and django extensions
django = "^4.0.4"
django-anymail = "^8.5"
django-environ = "^0.8.1"
django-extensions = "^3.1.5"
django-jazzmin = "^2.5.0"
django-stubs-ext = "^0.4.0"
whitenoise = "^6.0.0"

# Libs
celery = "^5.2.6"
iptools = "^0.7.0"
sentry-sdk = "^1.5.10"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
# Django
django-debug-toolbar = "^3.3.0"
django-extra-checks = "^0.11.0"
django-querycount = "^0.7.0"
werkzeug = "<2.1"  # needed for django_extensions runserver_plus

# Tests
hypothesis = "^6.46"
pytest = "^7.1"
pytest-django = "^4.5"
pytest-cov = "^3.0"
pytest-randomly = "^3.11"
pytest-deadfixtures = "^2.2"
pytest-testmon = "^1.3"
pytest-timeout = "^2.1"

# Linting
black = "^22.3.0"
flake8-black = "^0.3.2"
flake8-django = "^1.1.2"
flake8-isort = "^4.1.1"
flake8-logging-format = "^0.6.0"
pre-commit = "^2.18.1"
wemake-python-styleguide = "^0.16.1"

# Typing
mypy = "0.942"
django-stubs = "^1.10.1"
celery-types = "^0.13.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
# isort configuration:
# https://github.com/PyCQA/isort/wiki/isort-Settings
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
known_django = "django"
known_first_party = "app"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
skip_glob = [
  "**/node_modules/**",
  "**/migrations/*.py"
]
lines_between_types = 1
lines_after_imports = 2
combine_star = true

[tool.mypy]
# Mypy configuration:
# https://mypy.readthedocs.io/en/latest/config_file.html
allow_redefinition = false
check_untyped_defs = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

plugins = [
  "mypy_django_plugin.main"
]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "app.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "app.settings"

[tool.pytest.ini_options]
# pytest configuration:
# https://docs.pytest.org/en/stable/customize.html

# pytest-django configuration:
# https://pytest-django.readthedocs.io/en/latest/
DJANGO_SETTINGS_MODULE = "app.settings.test"

# Time out tests after this amount of seconds.
# https://pypi.org/project/pytest-timeout/
timeout = 5

# Strict `@xfail` by default
xfail_strict = true

# Directories that are ignored by the pytest collector
norecursedirs = "*.egg .eggs .git __pycache__ settings"

# Additional options to run with
addopts = [
  "--strict-markers",
  "--strict-config",
  "--doctest-modules",
  "--fail-on-template-vars",
  "--dup-fixtures",
  "--tb=short",
  "--cov=app",
  "--cov=tests",
  "--cov-branch",
  "--cov-report=term-missing:skip-covered",
  "--cov-report=html"
]
