[tool.poetry]
name = "django-starter"
version = "0.1.0"
description = ""
authors = ["Alexander Skrivanos <alex@skrivanos.se>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.4"
celery = "^5.2.6"
iptools = "^0.7.0"
sentry-sdk = "^1.5.10"
django-anymail = "^8.5"
django-environ = "^0.8.1"
django-extensions = "^3.1.5"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
coverage = "^6.3.2"
django-debug-toolbar = "^3.3.0"
factory-boy = "^3.2.1"
flake8-isort = "^4.1.1"
pre-commit = "^2.18.1"
Werkzeug = "<2.1"
flake8-black = "^0.3.2"
black = "^22.3.0"
darglint = "^1.8.1"
flake8-django = "^1.1.2"
flake8-logging-format = "^0.6.0"
wemake-python-styleguide = "^0.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
